Die on mksquashfs failure.
AppImage/AppImageKit pull request #1189
Opened 2022-04-03 06:15 UTC by lalten

This PR adds code to check the return code of the mksquashfs process. appimagekit will now die if mksquashfs failed.

2022-04-03 14:42 UTC, TheAssassin requested changes
Thanks, looks good overall. See my comment, applies to all `perror` calls.

2022-04-03 14:42 UTC, TheAssassin commented on src/appimagetool.c
> +        perror("fork()");
Please add some context information. We use other subprocesses, too, within the scope of AppImageKit. Ideally, the message informs the user that this was trying to open the `mksquashfs` process.

2022-08-18 14:39 UTC, lalten commented
ping on this one as well @TheAssassin :)

2022-08-18 14:40 UTC, TheAssassin commented
Will have a look. Haven't had time for AppImage related projects in a while, and when things broke I had to invest like a full week or maybe even two...

2022-08-18 14:42 UTC, TheAssassin commented on src/appimagetool.c
> +            fprintf(stderr, "mksquashfs (pid %ld) exited with code %d\n", (long)pid, retcode);
`pid_t` should be an `int` in glibc, so I'm not sure this cast is necessary, `%d` should work. (After all, `long int` and `int` are most likely the same size (4 bytes) on every viable platform anyway...)

2022-09-20 01:53 UTC, lalten commented
Friendly ping on this one, @TheAssassin :)

2022-09-29 12:45 UTC, TheAssassin approved these changes

2022-09-29 13:54 UTC, merged

2022-09-29 13:54 UTC, TheAssassin commented
Thanks!